### ISSUE TITLE
SpaceX Dashboard Challenge

### ISSUE THREAD

**Issue by abhimishra01** [abhimishra01/spacex-internship-challenge-for-Abhimishra#1]
https://public.3.basecamp.com/p/gTzefeJQh5Vf2g3LWbVfvyNe

**Comment by abhimishra01** [comment]
The application is ready for the code review

**Comment by kabir4691** [comment]
Avoid adding redundant comments like these. 

![Screenshot](https://user-images.githubusercontent.com/4736270/124221348-3f737d80-db1d-11eb-9ddf-6d589fc0638a.png)

Apart from that, the code looks good.

**Comment by abhimishra01** [comment]
Thank you sir for the review and your time.
